### ISSUE TITLE
Disallowed host response when hosted on development server

### ISSUE THREAD

**Issue by Rajdeep-Chakraborty0611** [CoderHaiBhai/projectHumara#1]
## debugging screen
![Screenshot 2024-03-15 223504](https://github.com/CoderHaiBhai/projectHumara/assets/152078159/2c6192eb-c99b-4f8d-919f-d92a3217d925)
## terminal output 
![Screenshot 2024-03-15 224015](https://github.com/CoderHaiBhai/projectHumara/assets/152078159/f6c3287b-d85a-4ead-a403-59f42705d15e)

**Comment by adi-tyasingh** [comment]
@Spy13x8  fixed bug in branch bugfix001
